add array key to prismic block
elgentos/magento2-prismicio pull request #108
Opened 2023-11-09 11:17 UTC by IvoElgentos

2023-11-10 07:45 UTC, WouterSteen requested changes
Is the change in block/Slice.php really needed? b/c seems like we dont do anything with it in that function?

2023-11-10 07:52 UTC, JeroenBoersma approved these changes
Thank you!

Nice submission, added a suggestion but looks good to me

2023-11-10 07:52 UTC, JeroenBoersma commented on Block/Slices.php
> +    public function fetchItem(\stdClass $slice, $key): string
:*suggestion* (non-blocking): you could add the `setIterator($key)` here too on the block after `setDocument`

2023-11-10 08:08 UTC, JeroenBoersma commented
> Is the change in block/Slice.php really needed? b/c seems like we dont do anything with it in that function?

yes, thought I could imagine that need to set a default for the field for backwards compatibility.

`$key = null;` to make sure that extension will not break.

effective
```php
function fetchItem(..., $key = null)
//...
null !== $key && $block->setIterator($key)
```

2023-11-16 09:50 UTC, JeroenBoersma commented
> Is the change in block/Slice.php really needed? b/c seems like we dont do anything with it in that function?

Yes because it overwrites the Grouped and those need to be compatible...

Can you review Wouter? Than we can merge this and tag it as a minor update :beers:

2023-11-20 08:25 UTC, WouterSteen approved these changes

2023-11-20 08:25 UTC, merged