Added a Category block
elgentos/magento2-prismicio pull request #76
Opened 2022-09-06 15:06 UTC by jesse-deboer

This PR adds a Category block to easily add Prismic content based on the current category. 

You just have to include the following inside your category xml and after that you can load all the blocks and slices of the current category:

```
<block name="category.prismic_content" class="Elgentos\PrismicIO\Block\StaticCategoryBlock">
      <arguments>
          <argument name="data" xsi:type="array">
              <item name="content_type" xsi:type="string">{your page type}</item>
          </argument>
      </arguments>
 </block>
````

The UID in Prismic should start with: `category-` and after that the number of the category you want to create the content for.

2022-09-06 16:06 UTC, ArjenMiedema requested changes

2022-09-06 16:06 UTC, ArjenMiedema commented on Block/StaticCategoryBlock.php
> +       return 'category-' . $this->layerResolver->get()->getCurrentCategory()->getId();
Please use `sprintf()` here

2022-09-07 06:50 UTC, JeroenBoersma commented on Block/StaticCategoryBlock.php
> +       return sprintf('category-%u', $this->layerResolver->get()->getCurrentCategory()->getId());
please put `$this->layerResolver->get()->getCurrentCategory()->getId())` in a seperate function and add a `hasCategory()`  so this won't throw an exeption

2022-09-07 06:59 UTC, JeroenBoersma commented
It looks like it mostly the same as `StaticBlock` we could also introduce a helper which could set the category id...

This would reduce the duplicate code we currently add...

```php

namespace Elgentos\PrismicIO\Helper

class CategoryIdToDocumentUid {
    constant PREFIX = 'category-';

   public function getUid(): string {
        return sprintf(seff::PREFIX . $this->layerResolver->get()->getCurrentCategory()->getId());
   }

}
```

in the xml you simple set

```xml
...
<block class="Elgentos\PrismicIO\Block\StaticBlock">
    <arguments>
        <argument name="uid" type="string" helper="Elgentos\PrismicIO\Helper\CategoryIdToDocumentUid::getUid" />
...
```

don't forget to add the check if you are in a category

2022-09-07 07:50 UTC, ArjenMiedema commented
> It looks like it mostly the same as `StaticBlock` we could also introduce a helper which could set the category id...
> 
> This would reduce the duplicate code we currently add...
> 
> ```
> namespace Elgentos\PrismicIO\Helper
> 
> class CategoryIdToDocumentUid {
>     constant PREFIX = 'category-';
> 
>    public function getUid(): string {
>         return sprintf(seff::PREFIX . $this->layerResolver->get()->getCurrentCategory()->getId());
>    }
> 
> }
> ```
> 
> in the xml you simple set
> 
> ```
> ...
> <block class="Elgentos\PrismicIO\Block\StaticBlock">
>     <arguments>
>         <argument name="uid" type="string" helper="Elgentos\PrismicIO\Helper\CategoryIdToDocumentUid::getUid" />
> ...
> ```
> 
> don't forget to add the check if you are in a category

@JeroenBoersma I'd not use a helper. If you want this to be available in a block, I'd go for a ViewModel here, since that is a better practice than using helpers.

2022-09-07 08:10 UTC, JeroenBoersma commented
that's just naming in this case... `ViewModels` are mostly used inside templates, in this case there won't be a template, in this case we just want a "method" (helper) to get a value...

So how I use it, only in `layout.xml` -> `Helper`, `Template.phtml` -> `ViewModel`

Either way it's fine with me, but it reduces the duplicate code, and we can also use this method for other cases. (content on product pages, content on checkout pages ...)

2022-09-07 08:22 UTC, ArjenMiedema commented
I discussed this with Jesse and he's working on a more generic approach now, so we don't need a new class at all.

2022-09-07 10:04 UTC, jesse-deboer commented
Duplicated code reduced by extending StaticBlock rather then AbstractBlock! 😄

2022-10-28 12:45 UTC, jesse-deboer commented
Closed in favour of #82

2022-10-28 12:45 UTC, closed without merging